# Reproduction of Adult dataset experiments

In this notebook we reproduce the results from Table 2 of the DECAF paper. We compare various methods for generating debiased data using the DECAF model against synthetic data generated using benchmark models GAN, WGAN-GP and FairGAN. As described in the paper we run all experiments (as implemented in this notebook) 10 times and avarage the results.

In [1]:
from sklearn.metrics import precision_score, recall_score, roc_auc_score
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier

from data import load_adult, preprocess_adult
from metrics import DP, FTU
from train import train_decaf, train_fairgan, train_vanilla_gan, train_wgan_gp
# import tensorflow as tf

import tensorflow as tf

print(tf.__version__)
tf.config.run_functions_eagerly(True)


/Users/alyssaunell/UvA_FACT2022/venv/lib/python3.8/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


2.4.4


## Loading data

In [2]:
dataset = load_adult()
dataset.head()

age         workclass    fnlwgt  education  education-num  \
0  39         State-gov   77516.0  Bachelors           13.0   
1  50  Self-emp-not-inc   83311.0  Bachelors           13.0   
2  38           Private  215646.0    HS-grad            9.0   
3  53           Private  234721.0       11th            7.0   
4  28           Private  338409.0  Bachelors           13.0   

       marital-status         occupation   relationship   race     sex  \
0       Never-married       Adm-clerical  Not-in-family  White    Male   
1  Married-civ-spouse    Exec-managerial        Husband  White    Male   
2            Divorced  Handlers-cleaners  Not-in-family  White    Male   
3  Married-civ-spouse  Handlers-cleaners        Husband  Black    Male   
4  Married-civ-spouse     Prof-specialty           Wife  Black  Female   

   capital-gain  capital-loss  hours-per-week native-country income  
0        2174.0           0.0            40.0  United-States  <=50K  
1           0.0           0.0            13.0  United-States  <=50K  
2           0.0           0.0            40.0  United-States  <=50K  
3           0.0           0.0            40.0  United-States  <=50K  
4           0.0           0.0            40.0           Cuba  <=50K

Preprocess the data next in order to make it suitable for training models on.

In [3]:
dataset = preprocess_adult(dataset)
dataset.head()

Split the dataset into train and test folds. Test fold size is 2000.

In [ ]:
datasetMat=dataset.corr()
print(datasetMat)
dataSeries = datasetMat.unstack().sort_values()
# print(dataSeries[dataSeries!=1][dataSeries>.2])
# print(dataSeries[dataSeries!=1][dataSeries<-.2])


                     age  workclass    fnlwgt  education  education-num  \
age             1.000000   0.132393 -0.075792   0.121167       0.037623   
workclass       0.132393   1.000000 -0.026970   0.031062       0.178857   
fnlwgt         -0.075792  -0.026970  1.000000   0.018028      -0.041993   
education       0.121167   0.031062  0.018028   1.000000      -0.232239   
education-num   0.037623   0.178857 -0.041993  -0.232239       1.000000   
marital-status -0.223313  -0.054065  0.027992  -0.012672      -0.099085   
occupation      0.028364   0.124357  0.004324   0.015018      -0.042766   
relationship    0.119980   0.008361  0.014071   0.032253      -0.032970   
race           -0.023444   0.037899  0.106732   0.008541      -0.077987   
sex             0.082053  -0.007633  0.027240   0.033126       0.003417   
capital-gain    0.079683   0.014562 -0.004110   0.027249       0.126907   
capital-loss    0.059351   0.019798 -0.004349   0.011847       0.081711   
hours-per-week  0.101992 

In [ ]:
# Split data into train and testing sets
dataset_train, dataset_test = train_test_split(dataset, test_size=2000,
                                               stratify=dataset['income'])

print('Size of train set:', len(dataset_train))
print('Size of test set:', len(dataset_test))

Size of train set: 43222
Size of test set: 2000


### Defining the DAG

We need to define a DAG which captures the biases of the dataset. As described in the DECAF paper normally a causal discovery algorithm is used. In this notebook we simply copy the DAG which as described in the Zhang et al. paper which is the one also used in the DECAF paper.

In [ ]:
# Define DAG for Adult dataset
dag = [
    ['income', 'education'],
    
    # Edges from race
    ['race', 'occupation'],
    ['race', 'income'],
    ['race', 'hours-per-week'],
    ['race', 'education'],
    ['race', 'marital-status'],

    # Edges from age
    ['age', 'occupation'],
    ['age', 'hours-per-week'],
    ['age', 'income'],
    ['age', 'workclass'],
    ['age', 'marital-status'],
    ['age', 'education'],
    ['age', 'relationship'],
    
    # Edges from sex
    ['sex', 'occupation'],
    ['sex', 'marital-status'],
    ['sex', 'income'],
    ['sex', 'workclass'],
    ['sex', 'education'],
    ['sex', 'relationship'],
    
    # Edges from native country
    ['native-country', 'marital-status'],
    ['native-country', 'hours-per-week'],
    ['native-country', 'education'],
    ['native-country', 'workclass'],
    ['native-country', 'income'],
    ['native-country', 'relationship'],
    
    # Edges from marital status
    ['marital-status', 'occupation'],
    ['marital-status', 'hours-per-week'],
    ['marital-status', 'income'],
    ['marital-status', 'workclass'],
    ['marital-status', 'relationship'],
    ['marital-status', 'education'],
    
    # Edges from education
    ['education', 'occupation'],
    ['education', 'hours-per-week'],
    ['education', 'income'],
    ['education', 'workclass'],
    ['education', 'relationship'],
    
    # All remaining edges
    ['occupation', 'income'],
    ['hours-per-week', 'income'],
    ['workclass', 'income'],
    ['relationship', 'income']

    # #added edges
    # ['income', 'education'],
    # ['education', 'race']
]

def dag_to_idx(df, dag):
    """Convert columns in a DAG to the corresponding indices."""

    dag_idx = []
    for edge in dag:
        dag_idx.append([df.columns.get_loc(edge[0]), df.columns.get_loc(edge[1])])

    return dag_idx

# Convert the DAG to one that can be provided to the DECAF model
dag_seed = dag_to_idx(dataset, dag)
print(dag_seed)
print(len(dag))

[[14, 3], [8, 6], [8, 14], [8, 12], [8, 3], [8, 5], [0, 6], [0, 12], [0, 14], [0, 1], [0, 5], [0, 3], [0, 7], [9, 6], [9, 5], [9, 14], [9, 1], [9, 3], [9, 7], [13, 5], [13, 12], [13, 3], [13, 1], [13, 14], [13, 7], [5, 6], [5, 12], [5, 14], [5, 1], [5, 7], [5, 3], [3, 6], [3, 12], [3, 14], [3, 1], [3, 7], [6, 14], [12, 14], [1, 14], [7, 14]]
40


# Identify Cycles

In [ ]:
maxNode=0
for edge in dag_seed:
    if max(edge)>maxNode:
        maxNode=max(edge)
    
dag_adj= [[-1]]*(maxNode+1)
dagStart=set()
for edge in dag_seed:
    if edge[0] not in dagStart:
        dagStart.add(edge[0])
        dag_adj[edge[0]]=[edge[1]]
    else:
        dag_adj[edge[0]].append(edge[1])
print(dag_adj)

[[6, 12, 14, 1, 5, 3, 7], [14], [-1], [6, 12, 14, 1, 7], [-1], [6, 12, 14, 1, 7, 3], [14], [14], [6, 14, 12, 3, 5], [6, 5, 14, 1, 3, 7], [-1], [-1], [14], [5, 12, 3, 1, 14, 7], [3]]


In [ ]:
# order=[]

# def findCycle(node, visited, stack):
#     order.append(node)
#     visited[node] = True
#     stack[node]=True
#     if dag_adj[node]==[-1]:
#         stack[node]=False
#         return (False, -1)
#     for adj in dag_adj[node]:
#         if visited[adj]==False:
#             if findCycle(adj, visited, stack)[0]:
#                 return (True, stack, visited)
#         elif stack[adj]==True:
#             return (True, 1)
#     stack[node]=False
#     return (False,0)

# def checkNodes(dag_adj):
#     visited = [False]*len(dag_adj)
#     stack = [False]*len(dag_adj)
#     for node in range(len(dag_adj)):
#         if not visited[node]:
#             output = findCycle(node, visited, stack)
#             if output[0]:
#                 return output
#     return False

# print(checkNodes(dag_adj))
# print(order)

# Collapse Graph

In [ ]:
#CODE TO DETECT DIFFERENCES BETWEEN 2 Dense graphs for debugging
a=tf.constant([[0., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0., 0., 1., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0., 1., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 1., 0., 0., 1., 1., 0., 0., 0., 0., 1., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 1., 0., 1.],
        [0., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 1., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 1., 0., 1.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]) #a with 2 cycles, 2 new one values

b= tf.constant([[0., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0., 0., 1., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 1., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 1., 0., 0., 1., 1., 0., 0., 0., 0., 1., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 1., 0., 1.],
        [0., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 1., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 1., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]) #b without cycle

print(a-b)


tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]], shape=(15, 15), dtype=float32)


2022-12-08 13:50:35.787213: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2022-12-08 13:50:35.788152: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


It's also necessary to define edges we want to remove from the DAG in order to meet the various fairness criteria described in the paper.

In [ ]:
def create_bias_dict(df, edge_map):
    """
    Convert the given edge tuples to a bias dict used for generating
    debiased synthetic data.
    """
    bias_dict = {}
    for key, val in edge_map.items():
        bias_dict[df.columns.get_loc(key)] = [df.columns.get_loc(f) for f in val]
    
    return bias_dict

# Bias dictionary to satisfy FTU
bias_dict_ftu = create_bias_dict(dataset, {'income': ['sex']})
print('Bias dict FTU:', bias_dict_ftu)

# Bias dictionary to satisfy DP
bias_dict_dp = create_bias_dict(dataset, {'income': [
    'occupation', 'hours-per-week', 'marital-status', 'education', 'sex',
    'workclass', 'relationship']})
print('Bias dict DP:', bias_dict_dp)

# Bias dictionary to satisfy CF
bias_dict_cf = create_bias_dict(dataset, {'income': [
    'marital-status', 'sex']})
print('Bias dict CF:', bias_dict_cf)

Bias dict FTU: {14: [9]}
Bias dict DP: {14: [6, 12, 5, 3, 9, 1, 7]}
Bias dict CF: {14: [5, 9]}


## Experiments

We have loaded and preprocessed the data and we are ready to run the experiments. For each experiment we train a generative model, sample synthetic data from the trained model and then obtain metrics by training and evaluating a downstream multi-layer perceptron using the test fold we generated in the previous section. We use the MLP model from `sklearn` with default parameters which matches the settings described in Appendix D of the paper.

In [ ]:
def eval_model(dataset_train, dataset_test):
    """Helper function that prints evaluation metrics."""

    X_train, y_train = dataset_train.drop(columns=['income']), dataset_train['income']
    X_test, y_test = dataset_test.drop(columns=['income']), dataset_test['income']

    clf = MLPClassifier()
    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)

    precision = precision_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    auroc = roc_auc_score(y_test, y_pred)
    dp = DP(clf, X_test)
    ftu = FTU(clf, X_test)

    return {'precision': precision, 'recall': recall, 'auroc': auroc,
            'dp': dp, 'ftu': ftu}

### Original dataset

As a benchmark we want to first train the downstream model on the original dataset.

In [ ]:
# eval_model(dataset_train, dataset_test)

In the following sections we train various models in order to reproduce the results from Table 2 of the DECAF paper.

### GAN

In [ ]:
# synth_data = train_vanilla_gan(dataset_train)
# synth_data.head()

In [ ]:
# eval_model(synth_data, dataset_test)

### WGAN-GP

In [ ]:
# synth_data = train_wgan_gp(dataset_train)
# synth_data.head()

In [ ]:
# eval_model(synth_data, dataset_test)

### FairGAN

In [ ]:
# synth_data = train_fairgan(dataset_train)
# synth_data.head()

In [ ]:
# eval_model(synth_data, dataset_test)

### DECAF

#### DECAF-ND

In [ ]:
synth_data = train_decaf(dataset_train, dag_seed)
synth_data.head()

/Users/alyssaunell/UvA_FACT2022/venv/lib/python3.8/site-packages/pytorch_lightning/core/datamodule.py:175: LightningDeprecationWarning: DataModule property `dims` was deprecated in v1.5 and will be removed in v1.7.
  rank_zero_deprecation("DataModule property `dims` was deprecated in v1.5 and will be removed in v1.7.")
/Users/alyssaunell/UvA_FACT2022/venv/lib/python3.8/site-packages/pytorch_lightning/core/datamodule.py:170: LightningDeprecationWarning: DataModule property `dims` was deprecated in v1.5 and will be removed in v1.7.
  rank_zero_deprecation("DataModule property `dims` was deprecated in v1.5 and will be removed in v1.7.")


Initialised adjacency matrix as parsed:
 Parameter containing:
tensor([[0., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0., 0., 1., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 1., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 1., 0., 0., 1., 1., 0., 0., 0., 0., 1., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 1., 0., 1.],
        [0., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 1., 0., 1., 0.

NameError: name 'h_dim' is not defined

In [ ]:
eval_model(synth_data, dataset_test)

{'precision': 0.8651851851851852,
 'recall': 0.776595744680851,
 'auroc': 0.7048301304049416,
 'dp': 0.29788303,
 'ftu': 0.109999955}

#### DECAF-FTU

In [ ]:
synth_data = train_decaf(dataset_train, dag_seed, biased_edges=bias_dict_ftu)
synth_data.head()

/Users/alyssaunell/UvA_FACT2022/venv/lib/python3.8/site-packages/pytorch_lightning/core/datamodule.py:175: LightningDeprecationWarning: DataModule property `dims` was deprecated in v1.5 and will be removed in v1.7.
  rank_zero_deprecation("DataModule property `dims` was deprecated in v1.5 and will be removed in v1.7.")
/Users/alyssaunell/UvA_FACT2022/venv/lib/python3.8/site-packages/pytorch_lightning/core/datamodule.py:170: LightningDeprecationWarning: DataModule property `dims` was deprecated in v1.5 and will be removed in v1.7.
  rank_zero_deprecation("DataModule property `dims` was deprecated in v1.5 and will be removed in v1.7.")


Initialised adjacency matrix as parsed:
 Parameter containing:
tensor([[0., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0., 0., 1., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0., 1., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 1., 0., 0., 1., 1., 0., 0., 0., 0., 1., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 1., 0., 1.],
        [0., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 1., 0., 1., 0.

age  workclass    fnlwgt  education  education-num  \
812    0.266254   0.022870  0.042094   0.214835       0.879316   
5967   0.463169   0.811339  0.075665   0.820674       0.631104   
22637  0.157099   0.644026  0.055997   0.208734       0.618299   
15499  0.467963   0.000997  0.123533   0.832090       0.477357   
19906  0.196508   0.000003  0.209058   0.052081       0.648811   

       marital-status  occupation  relationship          race  sex  \
812      2.907068e-01    0.194405      0.201390  6.843163e-19  1.0   
5967     3.693685e-09    0.198198      0.399914  5.113201e-28  1.0   
22637    3.029250e-01    0.149662      0.125950  2.752513e-18  0.0   
15499    5.460625e-11    0.102413      0.397683  6.668265e-34  1.0   
19906    2.910778e-01    0.815041      0.516874  9.650097e-37  1.0   

       capital-gain  capital-loss  hours-per-week  native-country  income  
812    4.539193e-14  2.552196e-16        0.617458    4.926280e-04     1.0  
5967   2.370380e-12  2.670368e-22        0.339417    1.264174e-19     0.0  
22637  5.823941e-17  9.478544e-12        0.367772    1.475993e-24     0.0  
15499  6.878430e-15  7.121354e-20        0.559213    3.039009e-13     1.0  
19906  1.168222e-07  3.795385e-06        0.226131    1.480822e-15     1.0

In [ ]:
eval_model(synth_data, dataset_test)

#### DECAF-CF

In [ ]:
synth_data = train_decaf(dataset_train, dag_seed, biased_edges=bias_dict_cf)
synth_data.head()

/Users/alyssaunell/UvA_FACT2022/venv/lib/python3.8/site-packages/pytorch_lightning/core/datamodule.py:175: LightningDeprecationWarning: DataModule property `dims` was deprecated in v1.5 and will be removed in v1.7.
  rank_zero_deprecation("DataModule property `dims` was deprecated in v1.5 and will be removed in v1.7.")
/Users/alyssaunell/UvA_FACT2022/venv/lib/python3.8/site-packages/pytorch_lightning/core/datamodule.py:170: LightningDeprecationWarning: DataModule property `dims` was deprecated in v1.5 and will be removed in v1.7.
  rank_zero_deprecation("DataModule property `dims` was deprecated in v1.5 and will be removed in v1.7.")


Initialised adjacency matrix as parsed:
 Parameter containing:
tensor([[0., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0., 0., 1., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0., 1., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 1., 0., 0., 1., 1., 0., 0., 0., 0., 1., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 1., 0., 1.],
        [0., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 1., 0., 1., 0.

age     workclass    fnlwgt  education  education-num  \
14048  0.188350  1.688214e-04  0.093547   0.041265       0.971950   
14590  0.106622  1.011682e-02  0.086411   0.181665       0.563363   
23858  0.211246  1.917130e-07  0.054367   0.030722       0.631940   
780    0.115459  3.878504e-07  0.062410   0.034999       0.963131   
15547  0.561209  1.120683e-01  0.078687   0.858158       0.488480   

       marital-status  occupation  relationship          race  sex  \
14048        0.288652    0.087973      0.326100  1.538513e-30  1.0   
14590        0.286136    0.482522      0.754618  3.104885e-15  1.0   
23858        0.288672    0.083053      0.703324  7.864906e-26  1.0   
780          0.270482    0.316779      0.041284  3.299533e-07  0.0   
15547        0.457073    0.220861      0.987832  4.819847e-23  0.0   

       capital-gain  capital-loss  hours-per-week  native-country  income  
14048  9.019098e-08  6.630502e-04        0.240153    4.250481e-09     1.0  
14590  1.115307e-09  2.214673e-01        0.331639    1.687875e-26     0.0  
23858  4.233765e-06  2.287603e-09        0.246762    2.196123e-11     0.0  
780    6.061675e-04  1.129459e-22        0.553476    2.504910e-19     1.0  
15547  1.967876e-03  1.740339e-01        0.314620    9.778274e-22     1.0

In [ ]:
eval_model(synth_data, dataset_test)

{'precision': 0.7714895888948211,
 'recall': 0.9607712765957447,
 'auroc': 0.5489340253946465,
 'dp': 0.026723623,
 'ftu': 0.016499996}

#### DECAF-DP

In [ ]:
synth_data = train_decaf(dataset_train, dag_seed, biased_edges=bias_dict_dp)
synth_data.head()

/Users/alyssaunell/UvA_FACT2022/venv/lib/python3.8/site-packages/pytorch_lightning/core/datamodule.py:175: LightningDeprecationWarning: DataModule property `dims` was deprecated in v1.5 and will be removed in v1.7.
  rank_zero_deprecation("DataModule property `dims` was deprecated in v1.5 and will be removed in v1.7.")
/Users/alyssaunell/UvA_FACT2022/venv/lib/python3.8/site-packages/pytorch_lightning/core/datamodule.py:170: LightningDeprecationWarning: DataModule property `dims` was deprecated in v1.5 and will be removed in v1.7.
  rank_zero_deprecation("DataModule property `dims` was deprecated in v1.5 and will be removed in v1.7.")


Initialised adjacency matrix as parsed:
 Parameter containing:
tensor([[0., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0., 0., 1., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0., 1., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 1., 0., 0., 1., 1., 0., 0., 0., 0., 1., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 1., 0., 1.],
        [0., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 1., 0., 1., 0.

age     workclass    fnlwgt  education  education-num  \
14048  0.178706  6.868240e-01  0.073524   0.039970       0.483234   
14590  0.303430  6.950489e-08  0.185627   0.054157       0.498580   
23858  0.274386  6.018996e-03  0.069567   0.143423       0.562086   
780    0.324166  4.213441e-01  0.072413   0.607543       0.479265   
15547  0.418044  2.367120e-02  0.131401   0.074534       0.535354   

       marital-status  occupation  relationship          race  sex  \
14048    2.923991e-01    0.364860      0.600087  9.417156e-18  1.0   
14590    2.931322e-01    0.250863      0.343016  0.000000e+00  1.0   
23858    1.858769e-09    0.098196      0.440008  1.494615e-01  1.0   
780      1.115209e-03    0.650338      0.178754  0.000000e+00  0.0   
15547    2.169359e-06    0.178980      0.403039  5.368275e-17  1.0   

       capital-gain  capital-loss  hours-per-week  native-country  income  
14048  4.695503e-13  4.510889e-08        0.200148    1.051372e-19     1.0  
14590  4.053533e-04  2.480250e-12        0.439412    2.627585e-21     0.0  
23858  1.212908e-13  1.558180e-17        0.733754    9.311341e-27     1.0  
780    2.986288e-17  1.686280e-09        0.355282    4.801889e-27     1.0  
15547  7.450151e-18  3.589154e-10        0.372395    1.145330e-15     1.0

In [ ]:
eval_model(synth_data, dataset_test)

{'precision': 0.7578729994837378,
 'recall': 0.976063829787234,
 'auroc': 0.515249656829101,
 'dp': 0.007920206,
 'ftu': 0.00049996376}